services:
  - type: web
    name: laravel-web
    env: docker
    plan: free
    autoDeploy: true
    rootDir: .
    buildCommand: ""
    startCommand: ""
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://docker-laravel-1.onrender.com
      - key: LOG_LEVEL
        value: info
      - key: FILESYSTEM_DISK
        value: public
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: database
      - key: DB_CONNECTION
        value: pgsql
      - key: APP_KEY
        sync: false
      - key: DB_HOST
        value: dpg-d2k5547diees73dahfmg-a
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: test_db_2g3m
      - key: DB_USERNAME
        value: test_db_2g3m_user
      - key: DB_PASSWORD
        sync: false
    healthCheckPath: /health
    postDeploy:
      - php artisan key:generate --show
      - php artisan migrate --force
      - php artisan storage:link || true
    disk:
      name: storage
      mountPath: /var/www/html/storage
      sizeGB: 1

  - type: worker
    name: laravel-worker
    env: docker
    plan: free
    autoDeploy: true
    dockerContext: .
    dockerfilePath: ./Dockerfile
    startCommand: php artisan queue:work --sleep=3 --tries=3 --timeout=90
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://docker-laravel-1.onrender.com
      - key: LOG_LEVEL
        value: info
      - key: FILESYSTEM_DISK
        value: public
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: database
      - key: DB_CONNECTION
        value: pgsql
      - key: APP_KEY
        sync: false
      - key: DB_HOST
        value: dpg-d2k5547diees73dahfmg-a
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: test_db_2g3m
      - key: DB_USERNAME
        value: test_db_2g3m_user
      - key: DB_PASSWORD
        sync: false

  - type: cron
    name: laravel-scheduler
    env: docker
    plan: free
    schedule: "* * * * *"
    dockerContext: .
    dockerfilePath: ./Dockerfile
    command: php artisan schedule:run
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://docker-laravel-1.onrender.com
      - key: LOG_LEVEL
        value: info
      - key: FILESYSTEM_DISK
        value: public
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: database
      - key: DB_CONNECTION
        value: pgsql
      - key: APP_KEY
        sync: false
      - key: DB_HOST
        value: dpg-d2k5547diees73dahfmg-a
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: test_db_2g3m
      - key: DB_USERNAME
        value: test_db_2g3m_user
      - key: DB_PASSWORD
        sync: false
